
For more info and how to connect from windows,
see https://docs.ycrc.yale.edu/clusters-at-yale/guides/jupyter/
MacOS or linux terminal command to create your ssh tunnel
ssh -N -f -L 8883:pn040:8883 anthony.meza@poseidon.whoi.edu
Windows MobaXterm info
Forwarded port:same as remote port Remote server: pn040
Remote port: 8883
SSH server: poseidon.whoi.edu
SSHlogin: anthony.meza
SSH port: 22
Use a Browser on your local machine to go to: localhost:8883 (prefix w/ https:// if using password) 
[I 2024-04-12 16:40:26.636 ServerApp] Package jupyterlab took 0.0000s to import
[I 2024-04-12 16:40:29.647 ServerApp] Package dask_labextension took 3.0099s to import
[W 2024-04-12 16:40:29.647 ServerApp] A `_jupyter_server_extension_points` function was not found in dask_labextension. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-04-12 16:40:29.685 ServerApp] Package jupyter_resource_usage took 0.0379s to import
[I 2024-04-12 16:40:29.704 ServerApp] Package jupyter_server_fileid took 0.0185s to import
[I 2024-04-12 16:40:29.705 ServerApp] Package jupyter_server_proxy took 0.0000s to import
[I 2024-04-12 16:40:29.775 ServerApp] Package jupyter_server_terminals took 0.0694s to import
[I 2024-04-12 16:40:29.964 ServerApp] Package jupyter_server_ydoc took 0.1885s to import
[I 2024-04-12 16:40:29.964 ServerApp] Package nbclassic took 0.0000s to import
[W 2024-04-12 16:40:29.978 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-04-12 16:40:29.979 ServerApp] Package notebook_shim took 0.0000s to import
[W 2024-04-12 16:40:29.979 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-04-12 16:40:34.196 ServerApp] Package panel.io.jupyter_server_extension took 4.2140s to import
[I 2024-04-12 16:40:34.197 ServerApp] dask_labextension | extension was successfully linked.
[I 2024-04-12 16:40:34.197 ServerApp] jupyter_resource_usage | extension was successfully linked.
[I 2024-04-12 16:40:34.206 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2024-04-12 16:40:34.206 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2024-04-12 16:40:34.213 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-04-12 16:40:34.219 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2024-04-12 16:40:34.229 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-04-12 16:40:34.239 ServerApp] nbclassic | extension was successfully linked.
[I 2024-04-12 16:40:36.390 ServerApp] Package jupyter_nbextensions_configurator took 0.3325s to import
[W 2024-04-12 16:40:36.390 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_nbextensions_configurator. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-04-12 16:40:36.390 ServerApp] jupyter_nbextensions_configurator | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
[I 2024-04-12 16:40:36.390 ServerApp] jupyter_nbextensions_configurator | extension was successfully linked.
[I 2024-04-12 16:40:36.391 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-04-12 16:40:36.391 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2024-04-12 16:40:36.529 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-04-12 16:40:36.529 ServerApp] dask_labextension | extension was successfully loaded.
[I 2024-04-12 16:40:36.530 ServerApp] [jupyter_nbextensions_configurator] enabled 0.6.1
[I 2024-04-12 16:40:36.530 ServerApp] jupyter_nbextensions_configurator | extension was successfully loaded.
[I 2024-04-12 16:40:36.531 ServerApp] jupyter_resource_usage | extension was successfully loaded.
[I 2024-04-12 16:40:36.531 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2024-04-12 16:40:36.531 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /scratch/anthony.meza/CM4X/CM4XTransientTracers
[I 2024-04-12 16:40:36.532 FileIdExtension] ArbitraryFileIdManager : Configured database path: /vortexfs1/home/anthony.meza/.local/share/jupyter/file_id_manager.db
[I 2024-04-12 16:40:36.534 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2024-04-12 16:40:36.534 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2024-04-12 16:40:36.567 FileIdExtension] Attached event listeners.
[I 2024-04-12 16:40:36.567 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2024-04-12 16:40:36.635 ServerApp] jupyter_server_proxy | extension was successfully loaded.
[I 2024-04-12 16:40:36.637 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-04-12 16:40:36.638 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2024-04-12 16:40:36.638 LabApp] JupyterLab extension loaded from /vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyterlab
[I 2024-04-12 16:40:36.638 LabApp] JupyterLab application directory is /vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/share/jupyter/lab
[I 2024-04-12 16:40:36.643 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-04-12 16:40:36.671 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-04-12 16:40:36.672 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2024-04-12 16:40:36.673 ServerApp] Serving notebooks from local directory: /scratch/anthony.meza/CM4X/CM4XTransientTracers
[I 2024-04-12 16:40:36.673 ServerApp] Jupyter Server 2.5.0 is running at:
[I 2024-04-12 16:40:36.673 ServerApp] http://pn040:8883/lab?token=bbe1872d34741be6112e589816e28f5e79a3e333f057c5f8
[I 2024-04-12 16:40:36.673 ServerApp]     http://127.0.0.1:8883/lab?token=bbe1872d34741be6112e589816e28f5e79a3e333f057c5f8
[I 2024-04-12 16:40:36.673 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-04-12 16:40:36.689 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///vortexfs1/home/anthony.meza/.local/share/jupyter/runtime/jpserver-200473-open.html
    Or copy and paste one of these URLs:
        http://pn040:8883/lab?token=bbe1872d34741be6112e589816e28f5e79a3e333f057c5f8
        http://127.0.0.1:8883/lab?token=bbe1872d34741be6112e589816e28f5e79a3e333f057c5f8
[I 2024-04-12 16:40:58.348 LabApp] Generating new user for token-authenticated request: cfa06f9f05ef417590b921b865e27d2c
[W 2024-04-12 16:41:02.335 LabApp] Could not determine jupyterlab build status without nodejs
[W 2024-04-12 16:41:03.379 ServerApp] wrote error: 'No such file or directory: ECCO_profiles_basin_trends.ipynb'
    Traceback (most recent call last):
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 877, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: ECCO_profiles_basin_trends.ipynb)
[W 2024-04-12 16:41:03.398 ServerApp] 404 GET /api/contents/ECCO_profiles_basin_trends.ipynb?content=0&1712954463359 (cfa06f9f05ef417590b921b865e27d2c@10.141.0.12) 20.54ms referer=http://127.0.0.1:8883/lab
[W 2024-04-12 16:41:03.401 ServerApp] wrote error: 'No such file or directory: src.py'
    Traceback (most recent call last):
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 877, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: src.py)
[W 2024-04-12 16:41:03.402 ServerApp] 404 GET /api/contents/src.py?content=0&1712954463359 (cfa06f9f05ef417590b921b865e27d2c@10.141.0.12) 2.93ms referer=http://127.0.0.1:8883/lab
[W 2024-04-12 16:41:51.536 ServerApp] wrote error: 'Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n<<<<<<< HEAD\\\\n   "...\')'
    Traceback (most recent call last):
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 889, in get
        model = await self._notebook_model(path, content=content)
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 842, in _notebook_model
        nb = await self._read_notebook(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 385, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n<<<<<<< HEAD\\n   "...'))
[W 2024-04-12 16:41:51.542 ServerApp] 400 GET /api/contents/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb?type=notebook&content=1&1712954511491 (cfa06f9f05ef417590b921b865e27d2c@10.141.0.12) 38.80ms referer=http://127.0.0.1:8883/lab/tree/GLODAP_comparisons
[I 2024-04-12 16:41:56.711 ServerApp] Kernel started: 59563dc8-94ea-4a93-8878-81eeb87740f5
[W 2024-04-12 16:41:57.010 ServerApp] wrote error: 'Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n<<<<<<< HEAD\\\\n   "...\')'
    Traceback (most recent call last):
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 889, in get
        model = await self._notebook_model(path, content=content)
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 842, in _notebook_model
        nb = await self._read_notebook(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 385, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n<<<<<<< HEAD\\n   "...'))
[W 2024-04-12 16:41:57.010 ServerApp] 400 GET /api/contents/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb?type=notebook&content=1&1712954516917 (cfa06f9f05ef417590b921b865e27d2c@10.141.0.12) 27.08ms referer=http://127.0.0.1:8883/lab/tree/GLODAP_comparisons/dev_section_timeseries_sigma2_old.ipynb
[W 2024-04-12 16:41:58.322 ServerApp] Could not destroy zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object at 0x2aabe3d17310>
[I 2024-04-12 16:41:58.370 ServerApp] Connecting to kernel 59563dc8-94ea-4a93-8878-81eeb87740f5.
[I 2024-04-12 16:41:58.409 ServerApp] Connecting to kernel 59563dc8-94ea-4a93-8878-81eeb87740f5.
[I 2024-04-12 16:41:58.441 ServerApp] Connecting to kernel 59563dc8-94ea-4a93-8878-81eeb87740f5.
[W 2024-04-12 16:41:59.650 ServerApp] wrote error: 'Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n<<<<<<< HEAD\\\\n   "...\')'
    Traceback (most recent call last):
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 889, in get
        model = await self._notebook_model(path, content=content)
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 842, in _notebook_model
        nb = await self._read_notebook(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 385, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n<<<<<<< HEAD\\n   "...'))
[W 2024-04-12 16:41:59.651 ServerApp] 400 GET /api/contents/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb?type=notebook&content=1&1712954519614 (cfa06f9f05ef417590b921b865e27d2c@10.141.0.12) 23.28ms referer=http://127.0.0.1:8883/lab/tree/GLODAP_comparisons/dev_section_timeseries_sigma2_old.ipynb
[W 2024-04-12 16:42:02.814 ServerApp] Notebook GLODAP_comparisons/dev_section_timeseries.ipynb is not trusted
[I 2024-04-12 16:42:03.327 ServerApp] Kernel started: 65b368c0-179a-43cb-b9ff-cab6a029f587
[W 2024-04-12 16:42:04.443 ServerApp] Could not destroy zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object at 0x2aabe3940070>
[I 2024-04-12 16:42:04.815 ServerApp] Connecting to kernel 65b368c0-179a-43cb-b9ff-cab6a029f587.
[I 2024-04-12 16:42:05.328 ServerApp] Kernel started: 37fb98c4-4d72-4987-93c6-2de0c2a232bb
[W 2024-04-12 16:42:06.391 ServerApp] Could not destroy zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object at 0x2aabe3940310>
[I 2024-04-12 16:42:06.442 ServerApp] Connecting to kernel 37fb98c4-4d72-4987-93c6-2de0c2a232bb.
[I 2024-04-12 16:42:07.359 ServerApp] Kernel started: 5fcffbc1-9b18-43ec-8946-db20d46c5291
[I 2024-04-12 16:42:07.386 ServerApp] Kernel started: e9032e2d-2f04-43e4-ba8f-a4fca841aabe
[W 2024-04-12 16:42:08.475 ServerApp] Could not destroy zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object at 0x2aabe3815780>
[W 2024-04-12 16:42:08.551 ServerApp] wrote error: 'Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/1.GLODAP_gridding.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n   "cell_type": "c...\')'
    Traceback (most recent call last):
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 889, in get
        model = await self._notebook_model(path, content=content)
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 842, in _notebook_model
        nb = await self._read_notebook(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 385, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/1.GLODAP_gridding.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "c...'))
[W 2024-04-12 16:42:08.552 ServerApp] 400 GET /api/contents/GLODAP_comparisons/1.GLODAP_gridding.ipynb?type=notebook&content=1&1712954527840 (cfa06f9f05ef417590b921b865e27d2c@10.141.0.12) 75.97ms referer=http://127.0.0.1:8883/lab/tree/GLODAP_comparisons/2.compare_hires_low_res.ipynb
[I 2024-04-12 16:42:08.563 ServerApp] Connecting to kernel 5fcffbc1-9b18-43ec-8946-db20d46c5291.
[I 2024-04-12 16:42:08.689 ServerApp] Connecting to kernel e9032e2d-2f04-43e4-ba8f-a4fca841aabe.
[I 2024-04-12 16:43:59.945 ServerApp] Starting buffering for 65b368c0-179a-43cb-b9ff-cab6a029f587:dac278d9-6e6d-4b49-9ed6-d374235db8ad
[I 2024-04-12 16:43:59.948 ServerApp] Starting buffering for 37fb98c4-4d72-4987-93c6-2de0c2a232bb:6b1096c7-c729-40ad-b436-2b0a9eaad35d
[I 2024-04-12 16:43:59.948 ServerApp] Starting buffering for e9032e2d-2f04-43e4-ba8f-a4fca841aabe:ce1ce710-9dfd-40c9-85a7-1fcf3df8062d
[I 2024-04-12 16:43:59.950 ServerApp] Starting buffering for 5fcffbc1-9b18-43ec-8946-db20d46c5291:8f3802eb-d128-4fdc-9e33-beba651342aa
[I 2024-04-12 16:43:59.950 ServerApp] Starting buffering for 59563dc8-94ea-4a93-8878-81eeb87740f5:b9b59e65-530f-4c0e-9467-5ab750c0d50f
[W 2024-04-12 16:44:01.811 LabApp] Could not determine jupyterlab build status without nodejs
[W 2024-04-12 16:44:02.702 ServerApp] Notebook GLODAP_comparisons/dev_section_timeseries.ipynb is not trusted
/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 2024-04-12 16:44:39.119 ServerApp] Could not destroy zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object at 0x2aabe37e5ed0>
[I 2024-04-12 16:44:39.140 ServerApp] Connecting to kernel 59563dc8-94ea-4a93-8878-81eeb87740f5.
[I 2024-04-12 16:44:39.178 ServerApp] Connecting to kernel 65b368c0-179a-43cb-b9ff-cab6a029f587.
[I 2024-04-12 16:44:39.217 ServerApp] Connecting to kernel e9032e2d-2f04-43e4-ba8f-a4fca841aabe.
[I 2024-04-12 16:44:39.218 ServerApp] Discarding 2 buffered messages for e9032e2d-2f04-43e4-ba8f-a4fca841aabe:ce1ce710-9dfd-40c9-85a7-1fcf3df8062d
[I 2024-04-12 16:44:39.259 ServerApp] Connecting to kernel 37fb98c4-4d72-4987-93c6-2de0c2a232bb.
[I 2024-04-12 16:44:39.305 ServerApp] Connecting to kernel 5fcffbc1-9b18-43ec-8946-db20d46c5291.
[W 2024-04-12 16:44:57.652 ServerApp] Could not destroy zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object at 0x2aabe37e6050>
[W 2024-04-12 16:44:59.619 ServerApp] wrote error: 'Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n<<<<<<< HEAD\\\\n   "...\')'
    Traceback (most recent call last):
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 889, in get
        model = await self._notebook_model(path, content=content)
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 842, in _notebook_model
        nb = await self._read_notebook(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 385, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n<<<<<<< HEAD\\n   "...'))
[W 2024-04-12 16:44:59.627 ServerApp] 400 GET /api/contents/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb?type=notebook&content=1&1712954699586 (cfa06f9f05ef417590b921b865e27d2c@10.141.0.12) 29.50ms referer=http://127.0.0.1:8883/lab/tree/GLODAP_comparisons/dev_section_timeseries.ipynb
[W 2024-04-12 16:47:40.562 ServerApp] wrote error: 'Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb NotJSONError(\'Notebook does not appear to be JSON: \\\'{\\\\n "cells": [\\\\n  {\\\\n<<<<<<< HEAD\\\\n   "...\')'
    Traceback (most recent call last):
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
        result = await obj
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 889, in get
        model = await self._notebook_model(path, content=content)
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 842, in _notebook_model
        nb = await self._read_notebook(
      File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/jupyter_server/services/contents/fileio.py", line 385, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /scratch/anthony.meza/CM4X/CM4XTransientTracers/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n<<<<<<< HEAD\\n   "...'))
[W 2024-04-12 16:47:40.566 ServerApp] 400 GET /api/contents/GLODAP_comparisons/dev_section_timeseries_sigma2.ipynb?type=notebook&content=1&1712954860522 (cfa06f9f05ef417590b921b865e27d2c@10.141.0.12) 36.27ms referer=http://127.0.0.1:8883/lab/tree/GLODAP_comparisons/dev_section_timeseries.ipynb
