2024-03-27 16:40:40,189 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.109:42035'
2024-03-27 16:40:41,903 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-3mh0dter', purging
2024-03-27 16:40:47,599 - distributed.worker - INFO -       Start worker at:   tcp://172.16.3.109:45167
2024-03-27 16:40:47,602 - distributed.worker - INFO -          Listening to:   tcp://172.16.3.109:45167
2024-03-27 16:40:47,602 - distributed.worker - INFO -           Worker name:             SLURMCluster-6
2024-03-27 16:40:47,602 - distributed.worker - INFO -          dashboard at:         172.16.3.109:38450
2024-03-27 16:40:47,602 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.54:32812
2024-03-27 16:40:47,602 - distributed.worker - INFO - -------------------------------------------------
2024-03-27 16:40:47,602 - distributed.worker - INFO -               Threads:                         36
2024-03-27 16:40:47,602 - distributed.worker - INFO -                Memory:                  37.25 GiB
2024-03-27 16:40:47,602 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-wq2x4x4q
2024-03-27 16:40:47,602 - distributed.worker - INFO - -------------------------------------------------
2024-03-27 16:40:47,633 - distributed.worker - INFO -         Registered to:    tcp://172.16.3.54:32812
2024-03-27 16:40:47,633 - distributed.worker - INFO - -------------------------------------------------
2024-03-27 16:40:47,634 - distributed.core - INFO - Starting established connection to tcp://172.16.3.54:32812
2024-03-27 16:41:37,041 - distributed.utils_perf - INFO - full garbage collection released 59.76 MiB from 1552 reference cycles (threshold: 9.54 MiB)
2024-03-27 18:25:52,713 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1269, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1028, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.16.3.109:59730 remote=tcp://172.16.3.54:32812>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-03-27 18:25:52,720 - distributed.core - INFO - Connection to tcp://172.16.3.54:32812 has been closed.
2024-03-27 18:25:52,720 - distributed.worker - INFO - Stopping worker at tcp://172.16.3.109:45167. Reason: worker-handle-scheduler-connection-broken
2024-03-27 18:25:52,725 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.16.3.109:42035'. Reason: worker-handle-scheduler-connection-broken
2024-03-27 18:25:52,734 - distributed.nanny - INFO - Worker closed
2024-03-27 18:25:54,739 - distributed.nanny - ERROR - Worker process died unexpectedly
2024-03-27 18:25:55,528 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.16.3.109:42035'. Reason: nanny-close-gracefully
2024-03-27 18:25:55,529 - distributed.dask_worker - INFO - End worker
