2024-03-26 21:53:30,821 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.172:38970'
2024-03-26 21:53:31,402 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-7fzvwog8', purging
2024-03-26 21:53:32,484 - distributed.worker - INFO -       Start worker at:   tcp://172.16.3.172:41327
2024-03-26 21:53:32,485 - distributed.worker - INFO -          Listening to:   tcp://172.16.3.172:41327
2024-03-26 21:53:32,485 - distributed.worker - INFO -           Worker name:            SLURMCluster-15
2024-03-26 21:53:32,485 - distributed.worker - INFO -          dashboard at:         172.16.3.172:40190
2024-03-26 21:53:32,485 - distributed.worker - INFO - Waiting to connect to:   tcp://172.16.3.103:38208
2024-03-26 21:53:32,485 - distributed.worker - INFO - -------------------------------------------------
2024-03-26 21:53:32,485 - distributed.worker - INFO -               Threads:                         36
2024-03-26 21:53:32,485 - distributed.worker - INFO -                Memory:                 178.81 GiB
2024-03-26 21:53:32,485 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-qxtlzzrv
2024-03-26 21:53:32,485 - distributed.worker - INFO - -------------------------------------------------
2024-03-26 21:53:32,501 - distributed.worker - INFO -         Registered to:   tcp://172.16.3.103:38208
2024-03-26 21:53:32,501 - distributed.worker - INFO - -------------------------------------------------
2024-03-26 21:53:32,502 - distributed.core - INFO - Starting established connection to tcp://172.16.3.103:38208
2024-03-26 22:06:27,555 - distributed.utils_perf - INFO - full garbage collection released 10.56 MiB from 1754 reference cycles (threshold: 9.54 MiB)
2024-03-26 22:59:11,313 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1269, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/core.py", line 1028, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.16.3.172:37601 remote=tcp://172.16.3.103:38208>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-03-26 22:59:11,332 - distributed.core - INFO - Connection to tcp://172.16.3.103:38208 has been closed.
2024-03-26 22:59:11,333 - distributed.worker - INFO - Stopping worker at tcp://172.16.3.172:41327. Reason: worker-handle-scheduler-connection-broken
2024-03-26 22:59:11,336 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.16.3.172:38970'. Reason: worker-handle-scheduler-connection-broken
2024-03-26 22:59:11,343 - distributed.nanny - INFO - Worker closed
2024-03-26 22:59:13,346 - distributed.nanny - ERROR - Worker process died unexpectedly
2024-03-26 22:59:13,625 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.16.3.172:38970'. Reason: nanny-close-gracefully
2024-03-26 22:59:13,626 - distributed.dask_worker - INFO - End worker
